### ISSUE TITLE
Add missing localization

### ISSUE THREAD

**Issue by Xottab-DUTY** [Keridos/FloodLights#25]
There is some text, that defined directly in the code. Can you move that text to the localization files?

P.S.: Text like: "Time remaining: 0m0sec", "Mode: Straight/Cone Narrow/Cone Wide", "Inverted: true/false"

**Comment by Keridos** [comment]
Gonna do that soonish, just need to figure out a way to do that

**Comment by Xottab-DUTY** [comment]
Ok!

**Comment by Keridos** [comment]
I let the time be displayed as 0m0s ok?

**Comment by Xottab-DUTY** [comment]
In principle, this is not important, but it would be nice if I could translate this text. (minutes and seconds to russian words) :smiley:

**Comment by Keridos** [comment]
problem with words would simply be too long for the GUI.

**Comment by Xottab-DUTY** [comment]
m&s to russian m&s maybe then? :D

**Comment by Keridos** [comment]
That would be ok, I am gonna add this in too, the commit should be popping up soonish.

**Comment by Xottab-DUTY** [comment]
Ok!

**Comment by Keridos** [comment]
Its ready now!
