### ISSUE TITLE
IGW-Mod using wrong subfolder when viewing block from different mod

### ISSUE THREAD

**Issue by blockbreaker1361** [Keridos/FloodLights#38]
I'm not getting any info on the IGW mod. Here is pic for proof. Both mods are latest versions.
http://imgur.com/Zeki5E5

**Comment by Keridos** [comment]
Update your igwmod, I think you use an old version of it.

**Comment by blockbreaker1361** [comment]
I'm using latest version of both mods.

**Comment by Keridos** [comment]
This seeems to be caused by IGWmod.

**Comment by Keridos** [comment]
Is fixed in igwmod 1.1.7-26. Also updated igwmod compatability again, so everything runs smooth with the new version.
