### ISSUE TITLE
Server crash on world start

### ISSUE THREAD

**Issue by BBoldt** [Keridos/FloodLights#39]
https://gist.github.com/60ee00834307fb32676a

**Comment by Keridos** [comment]
Try the newest build from the curseforge page please.

**Comment by BBoldt** [comment]
It's in the crashlog:

FloodLights{0.6.3-87} [Flood Lights] (FloodLights-1.7.10-0.6.3-87.jar)

**Comment by BBoldt** [comment]
I'll try the new version and get back to you

**Comment by Keridos** [comment]
I know that it is in the logs, but it is far easier for the mod makers if you just write the used version in the issue so we do not have to search for that in the logfiles.

**Comment by BBoldt** [comment]
Sorry. 

Anyways, latest version solves this issue.

**Comment by Keridos** [comment]
Glad to hear that, have fun!
And btw. no need to say sorry, would just be nice, if you considered doing that next time :)

**Comment by BBoldt** [comment]
@Keridos 

A user is getting the same issue again, on server startup: http://pastebin.com/8GyceatR

FloodLights-1.7.10-0.6.5-90.jar

**Comment by Keridos** [comment]
Try this please: https://www.ironhide.de/jenkins/job/FloodLights/lastSuccessfulBuild/artifact/build/libs/FloodLights-1.7.10-0.6.6-91.jar
