### ISSUE TITLE
Energy usage broken in release version

### ISSUE THREAD

**Issue by Forecaster** [Keridos/FloodLights#44]
You fixed it in experimental I believe, but then you added some fix to the release and had be switch to that, so now energy usage is broken again and the lights use way way more power than they should.

I had to remove the single light that was on the power line to my ore processing setup because it prevented the ore processing machines from getting enough power.

**Comment by Keridos** [comment]
That is weird, both branches should have the proper energy usage thingies, gonna check that.

**Comment by Forecaster** [comment]
Maybe I have the wrong version...

I'll have to verify that when I get home.

**Comment by Forecaster** [comment]
I have build 96 of non-dev floodlights.

**Comment by Keridos** [comment]
Try the Dev version, it should have all the fixes included and an additional fix, the whole complicated lighting code is gone. Lights are now way faster, less random lagspikes and overhead. And you can place cells in them.

**Comment by Keridos** [comment]
Fixed it now, also I think I found the issue with the EU-Reader. Mine is showing normal values now.
