### ISSUE TITLE
Camouflage ignoring block sub ids

### ISSUE THREAD

**Issue by mskurnik** [Keridos/FloodLights#47]
When you right click on a base to add a disguise, the base ignores the sub I'd of the block in your hand. For example attempting to use a block with ID 999:4 ends up inserting ID 999:0. I am not at the computer right now but it at least happens with third party blocks such as railcraft quarried blocks and natura blocks.  I have not tested with vanilla blocks.

**Comment by Keridos** [comment]
This is the wrong mod :P

**Comment by mskurnik** [comment]
Well I feel like a derp.  Sorry about that.

**Comment by Keridos** [comment]
No Problem :)
