### ISSUE TITLE
TileEntityElectricFloodlight causing 1100ms+ TPS spikes and 22 second can't keep ups on the server

### ISSUE THREAD

**Issue by mskurnik** [Keridos/FloodLights#50]
After getting 22 seconds worth of constant can't keep ups, I used the VisualVM tool to check what was causing the lag.  The entries below are causing an insane amount of lag

>de.keridos.floodlights.tileentity.TileEntityElectricFloodlight.removeSource()	70.46779	918 ms (70.5%)	241
de.keridos.floodlights.tileentity.TileEntityElectricFloodlight.addSource()	16.666641	217 ms (16.7%)	57

**Comment by Keridos** [comment]
I think I encountered this issue in my local environment as well, already working on a fix for this.

**Comment by Keridos** [comment]
Test this build please: https://www.ironhide.de/jenkins/job/FloodLights/107/

**Comment by mskurnik** [comment]
Well I just put 107 on there and that seemed to fix it.  I'll update to 108 later tonight.  Thanks!
