### ISSUE TITLE
[Enhancement] Debug option to trace down buggy "light" entities

### ISSUE THREAD

**Issue by spannerman79** [Keridos/FloodLights#51]
Forge 1448
[FloodLights-1.7.10-1.0.1-110.jar](http://minecraft.curseforge.com/mc-mods/224728-floodlights/files/2257273)

Perhaps an item (only available via Creative tab) that can be used to actually see the light "entities" to track down possible mod conflicts or lightning conflicts

See screenshot for example
![2015-09-17_16 26 04](https://cloud.githubusercontent.com/assets/7542384/9926518/7daaa896-5d59-11e5-897c-0cd884cf5f97.png)

That was taken after the floodlight (electric) was switched off.

**Comment by Keridos** [comment]
Which mode was the light on?

**Comment by spannerman79** [comment]
I will when its not so late for me (I'm UTC+10 - 10.30pm ) 

And i tried both cone modes (narrow and wide) - both have similar effects in different areas where there was no floodlight in the area (i moved 30 chunks away for each one)

The only way i can "destroy" those rogue light sources is placing blocks down until the block placement removes/destroys the light "entity"

But I will say that world save was from a version FloodLights-1.7.10-0.6.8-96.jar -> FloodLights-1.7.10-1.0.1-110.jar

**Comment by Keridos** [comment]
Should not happen, I reset the blocks internal name from that version so all lights should get destroyed. In the newer version I added in a check if setting the block to air failed and if it does the light should update itself until it is able to do that.

**Comment by spannerman79** [comment]
:+1: The newer build (114) works like a charm.

For reference the glass blocks were AE2's [Quartz Glass](http://ae-mod.info/Quartz-Glass/) blocks that the light "cones" were shining through.

**Comment by Keridos** [comment]
Hm what is your issue?

**Comment by Keridos** [comment]
This is most likely a client side desync. I have no idea where it comes from though.

**Comment by L-Clouds** [comment]
For what it's worth, I was just coming back to Minecraft and tried 1.7.10-1.0.2-43 and had problems with illumination not completely updating, too (phantom light that got left behind when switching modes).  I tried in single player, both with and without FastCraft...

The last version I'd tried before was way back at 1.7.10-0.3.7-51 and it doesn't have this problem.  So, something that was changed between these versions may be the cause?

Forge 10.13.4.1448 and Java 7-64

**Comment by Keridos** [comment]
Weird thing I figured out. In my dev env it bugs too, though apparently the blocks lighting up are air. Seems to be a client desync as rejoining the world / rejoining the server seems to fix it.

Still have the code for the client side phantom light debug tool. Works (but a bit buggy still) and shows the entities. Gonna leave this issue open for a later build.
