### ISSUE TITLE
Client light desync after switching off/changing floodlight mode

### ISSUE THREAD

**Issue by Voker57** [Keridos/FloodLights#57]
If you turn off the floodlight or change its mode, some 'light sources' still stay. Fixed by reconnecting to server. Screenshot: http://dump.bitcheese.net/files/ideposo/2016-02-21_22.31.13.png

Minecraft 1.7.10, Floodlights 1.1.1, other mods: industrialcraft, project red, buildcraft, computercraft.

**Comment by Keridos** [comment]
This is some kind of MC/Forge bug, Galacticraft has the same because for some reason light values do not correctly update on block sets and even after block updates. No idea how to fix this, same for the Galacricraft Dev if I remember correctly.

**Comment by drzpk** [comment]
This issue still occurs in 1.12.2. It may be caused by updating too many light-emitting blocks simultaneously. I'have added a workaround though.
