### ISSUE TITLE
floodlights disconnect themselves from ic2 energy network

### ISSUE THREAD

**Issue by Voker57** [Keridos/FloodLights#58]
After some time running (don't think it's some specific action that triggers it) floodlights stop receiving energy from ic2 energy network they are attached to. Restarting the server solves the problem, as does replacing floodlights.

Also, this message appears in server log on mod load: 

```
[01:44:17] [Server thread/WARN] [IC2.EnergyNet]: EnergyNet.addTileEntity: de.keridos.floodlights.tileentity.TileEntityElectricFloodlight@77fd30ce (de.keridos.floodlights.tileentity.TileEntityElectricFloodlight@77fd30ce) is still conflicting with de.keridos.floodlights.tileentity.TileEntityElectricFloodlight@6af3024a using the same position (overlapping), aborting
```

**Comment by Keridos** [comment]
How often does this happen?

**Comment by Voker57** [comment]
it appears to be random, sometimes you play whole day and it's fine, sometimes after several minutes.

Also, the message actually appears when bug manifests, not on load.

**Comment by Keridos** [comment]
Do you use vanilla forge or cauldron?

**Comment by spannerman79** [comment]
@Keridos there is also Thermos - a fork of KCauldron to consider as well

**Comment by Voker57** [comment]
vanilla Forge10.13.4.1614. Here's my mod list:

`ComputerCraft@1.75,flansmod@4.10.0,malisiscore@1.7.10-0.14.1,NotEnoughItems@1.0.3.74,ProjRed|Compatibility@4.7.0pre12.95,ForgeRelocation@0.0.1.4,CCTweaks@0.3.0.2,BuildCraft|Silicon@7.1.14,MrTJPCoreMod@1.1.0.33,Forge@10.13.4.1614,IronChest@6.0.60.741,ProjRed|Expansion@4.7.0pre12.95,ForgeMicroblock@1.2.0.345,BuildCraft|Core@7.1.14,CodeChickenCore@1.0.4.29,ProjRed|Integration@4.7.0pre12.95,BuildCraft|Energy@7.1.14,RelocationFMP@0.0.1.2,IC2@2.2.815-experimental,mcp@9.05,ProjRed|Transmission@4.7.0pre12.95,journeymap@5.1.3,<CCTweaks ASM>@0.3.0.2,BuildCraft|Robotics@7.1.14,ProjRed|Transportation@4.7.0pre12.95,FML@7.10.99.99,inventorytweaks@1.59-dev-152-cf6e263,BuildCraft|Transport@7.1.14,McMultipart@1.2.0.345,cfm@3.4.8,ProjRed|Fabrication@4.7.0pre12.95,BuildCraft|Factory@7.1.14,ProjRed|Core@4.7.0pre12.95,FloodLights@1.1.1-120,ProjRed|Illumination@4.7.0pre12.95,IC2NuclearControl@2.3.4a,Forestry@4.2.6.54,weaponmod@v1.14.3,DyeableBeds@1.7.2 R2,ForgeMultipart@1.2.0.345,malisisdoors@1.7.10-1.13.0,BuildCraft|Builders@7.1.14,OCS@1.7.5,MCFrames@1.0`

**Comment by Keridos** [comment]
Kind of weird, I am pretty much doing the IC2 energy stuff by the book. Gonna poke some IC2 Dev to see if I made a mistake there.
Maybe its some issue with forge though, can you test with the recommended forge build (10.13.4.1558)?

**Comment by Voker57** [comment]
no, some of these mods require newer forge. could try floodlights alone though

**Comment by Keridos** [comment]
Can you try this: https://jenkins.ironhide.de/job/FloodLights-1.7.10/136/ ?
