### ISSUE TITLE
IC2 integration

### ISSUE THREAD

**Issue by polarbear316** [Keridos/FloodLights#64]
Was testing out the Electric lights and noticed I couldn't add any IC2 energy items to the lights. Then looked at your code and seen all, or well most, of the IC2 code commented out. Are you taking IC2 support out, waiting for a release build, or just haven't got to that yet? 

Built a version using IC2's [2.5.24-ex19](http://jenkins.ic2.player.to/job/IC2_19/) 1.9.x build and seems to be working for the most part in single player.

**Comment by Keridos** [comment]
Gonna add that in, thanks, did not know IC2 already had aworking 1.9 port.
