### ISSUE TITLE
Unofficial Unity styled texture addon

### ISSUE THREAD

**Issue by ruyanve** [Keridos/FloodLights#66]
So I've been using this mod since forever and always hated the textures (no offense).
A while ago I made some simple replacements using Unity assets and asked the guys to have a look at your textures for a more professional approach, 
In the meantime anyone who wants, may of course use the ones I made:
http://imgur.com/a/Gmskn

Cheers

**Comment by Keridos** [comment]
Question, who has the rights to those textures? If possible I would ask if I can incorporate them into the main mod and replace my textures. My textures to be honest always were not that good since I am quite terrible at drawing, so no offense taken.

**Comment by spannerman79** [comment]
@Keridos https://github.com/CyanideX/Unity perhaps

**Comment by ruyanve** [comment]
I wrote Cyanide a message on twitter, hopefully he'll come by and give a green light... or even better someone on his crew has a look at the textures, because mine are not really good enough as default textures.

**Comment by CyanideX** [comment]
You're free to use any of our Unity assets. :)
