### ISSUE TITLE
Issue: Walking into a grow light from underneath causes texture issues

### ISSUE THREAD

**Issue by RainbowGravity** [Keridos/FloodLights#71]
Basically, the black and purple no texture thing covers the entire screen. Also happens when you fall  through the light. (intended?)

**Comment by Keridos** [comment]
You can walk through them and that is intended. The texture bug is not though, it might be possible to just do not render it from the inside maybe.

**Comment by RainbowGravity** [comment]
Newest Version on 1.10.2

**Comment by Keridos** [comment]
You should never report latest or newest version for bug reports. Please always tell the modders the exact version on which forge version.
