### ISSUE TITLE
Allow EIO wireless charger to power lights.

### ISSUE THREAD

**Issue by crawln45** [Keridos/FloodLights#73]
Thought allowing the ender IO's wireless charger to power the lights might be a nice. Not sure if it's possible or not. or possibly adding in a wireless power source to keep from having to run conduit/other through the roof everywhere.

**Comment by Keridos** [comment]
I have been actually thinking about that too and it already is on my planned features :)

**Comment by slappertins** [comment]
Hey uh just wondering if this is still going to be a feature in the future?

**Comment by Josh65-2201** [comment]
I would like this too just wondering if there's been an update on this.
