### ISSUE TITLE
CoFH API in FL Causes Crash

### ISSUE THREAD

**Issue by ElvenChaos** [Keridos/FloodLights#74]
This one is a little specific, but when Flood Lights, Botania, and Refined Storage are all in the same modpack, there is a crash relating to the CoFH API that is included in the FL .jar

If any one of the three mods are removed, then there is no crash.

Crash Logs:
http://pastebin.com/piJ6FsvN

**Comment by Keridos** [comment]
My best guess is that someone else is using an inofficial version that differs from my version of the API. My version is pretty much the same as RedstoneFluxed used (and that is a direct port from the 1.8 API with pretty much 0 changes codewise except for two lines). Currently I have no idea what could cause this and I am sure that other mods have the same API as I provide inside of their JARs.

**Comment by drzpk** [comment]
This issue is out-of-date: since 1.12.2 FloodLights uses Forge Energy API.
