### ISSUE TITLE
Can't change mode?

### ISSUE THREAD

**Issue by AnZaNaMa** [Keridos/FloodLights#75]
So I've got a floodlight and I've been trying to change the mode of it for forever. I have forestry, enderio, ic2, etc installed as well and I've been trying to use all the wrenches to change the mode of the light. Looking at the code, some of the mods wrench codes were commented out, but the EnderIO one is in there for sure. The only problem is that all the wrenches rotate the block when you right click on the floodlight. Also, the change mode method must not be firing, because i'm not getting any chat messages. I think it would be cool if I could still use the stick even with mods installed.

**Comment by Keridos** [comment]
Test this build please: https://jenkins.ironhide.de/job/FloodLights-1.10.2/7/

**Comment by Keridos** [comment]
@IlynPayne you can push changes to here now and should be able to administer the issue tracker. I will setup a build for this mod on jenkins.ironhide.de

**Comment by drzpk** [comment]
@Keridos OK, thanks.
