### ISSUE TITLE
Floodlight causes random crash

### ISSUE THREAD

**Issue by SylveonBottle** [Keridos/FloodLights#78]
No idea what is wrong, how this is happening, or how to reproduce. All I know is that the server seems to crash when it is lagging, and the crash log says it's by floodlight.

[crash-2017-01-03_14.46.45-server.txt](https://github.com/Keridos/FloodLights/files/683214/crash-2017-01-03_14.46.45-server.txt)

**Comment by drzpk** [comment]
Classes from the stack trace have been almost completely rewritten in 1.12.2, making this crashlog pretty much useless. If you're experiencing similar crashes in 1.12.2, feel free to open a new issue.

**Comment by SeasonalFerret** [comment]
I'd complain about the practice of just leaving bug reports open until they're invalid, but I've really moved on from Minecraft at this point.

**Comment by drzpk** [comment]
@SylveonBottle 
Well, this mod had been inactive almost 2 years until I took it over. And the first thing I did after that was to port the mod to 1.12.2 and rewrite some core logic. And that fixed some old issues (and possibly created new ones).
