### ISSUE TITLE
Grow Lights causing server log spam

### ISSUE THREAD

**Issue by FSDel** [Keridos/FloodLights#80]
A player recently started using floodlights, in particular, grow lights.

I am now getting significant log spam of the following lines:

de.keridos.floodlights.util.GeneralUtil isBlockValidGrowable
INFO: blockcangrow: true

Versions:
Minecraft 1.10.2
FloodLights-1.9.4-1.2.7-145

**Comment by Keridos** [comment]
fixed in latest release.
