### ISSUE TITLE
crash on tabcomplete

### ISSUE THREAD

**Issue by ExplodingONC** [Keridos/FloodLights#82]
[2018-09-10-2.log](https://github.com/Keridos/FloodLights/files/2364562/2018-09-10-2.log)

Cause a crash when I'm typing a command and press Tab to auto complete it.
This happens both in local worlds and on a server after I installed this mod, and go back to normal after I removed it.
The game log is attached above.
I really like this mod, and I hope that this problem is going to be fixed soon.

**Comment by Keridos** [comment]
We do not register any commands as far as I know. We could remove the IGW notifier but I doubt it has anything to do with it.

**Comment by ExplodingONC** [comment]
It is really strange I think, this mod do not have built-in commands, but it did crash some how. 
And I don't think that there is a conflict with other mods, because only this mod alone can still cause the crash.
I'm using Forge 14.23.4.2705 on Minecraft 1.12.2, and I hope this information can help you.

**Comment by drzpk** [comment]
> We could remove the IGW notifier but I doubt it has anything to do with it

@Keridos 
Actually, it did. Apparently API has changed since the last time the notifier was updated.

@ExplodingONC 
The issue should be now fixed. You can download the most recent artifact from [Jenkins](https://jenkins.ironhide.de/job/Keridos%20Mods/job/FloodLights-1.12/8/).

**Comment by ExplodingONC** [comment]
The crash issue is now solved by the 1.3.2 update, but this update seems to no longer work with sponge server. The error log is attached. Do you have any ideas?
[server log.txt](https://github.com/Keridos/FloodLights/files/2386267/server.log.txt)

**Comment by drzpk** [comment]
@ExplodingONC 
This is actually caused by one of the previous commits (most likely [e4f45a1](https://github.com/Keridos/FloodLights/commit/e4f45a19f16c03a6911e22e07f71bbcc2cc947c2)). I'll look into it.

**Comment by drzpk** [comment]
@ExplodingONC 
The issue with Sponge is now solved. Try the most recent build from Jenkins.

**Comment by ExplodingONC** [comment]
Everything is functioning properly now, thanks for your updates.
