### ISSUE TITLE
Grow light acts like straight flood light

### ISSUE THREAD

**Issue by Wolf68k** [Keridos/FloodLights#83]
While trying out the different lights in creative, and with the debug tool. When I placed a grow light and turned it on it lit up like the standard flood light does with a straight beam, even the debug showed it that way. When I turned off the grow light, the light was still there. And the light it still there even after the grow light block is removed.
Included a [screen shot](https://imgur.com/a/JrRJXTA). The purple block is a creative energy cell, the grow light was next to that, the grass block a place for me to place a lever to turn it on/off.

**Comment by Keridos** [comment]
https://github.com/Keridos/FloodLights/blob/1.12.2/src/main/java/de/keridos/floodlights/tileentity/TileEntityGrowLight.java#L21

**Comment by drzpk** [comment]
@Keridos 
That doesn't prove anything, besides, the next line sets the range to 1.

@Wolf68k 
You may experience such issues if you're using version from CurseForge, which is contains some issues. I'll upload a fresh version there soon. In the meantime, you can download the most recent build from Jenkins (link in the project README), which should be free of such bugs.

**Comment by Wolf68k** [comment]
I tried FloodLights-1.12.2-1.3.2-9 (sorry I forgot to mention I was using FloodLights-1.12.2-1.3.1-1 before).
That fixed the grow light problem, it also forces the lever to be either placed on the grow light or on a block directly next to the light for it to work. So where I showed where I originally had the lever in my screenshot, that no longer works.

There is still however the light that was left behind. The work around for that is to place a flood light where the defective grow light was, turn it on and off. I didn't think to do this with the previous version.

**Comment by drzpk** [comment]
> it also forces the lever to be either placed on the grow light or on a block directly next to the light for it to work

@Wolf68k 
I'll see what's wrong.

> There is still however the light that was left behind. The work around for that is to place a flood light where the defective grow light was, turn it on and off. I didn't think to do this with the previous version.

I've made modifications to minimize such cases. But nonetheless, periodical checks to light sources have been added, so the orphaned ones should disappear over time.

**Comment by drzpk** [comment]
> it also forces the lever to be either placed on the grow light or on a block directly next to the light for it to work

@Wolf68k 
But isn't that a correct behavior?
![grow_light](https://user-images.githubusercontent.com/27144202/46303081-2e336600-c5ab-11e8-9c27-f74cd385dfdf.png)

Anyhow, issue reported in this thread is fixed, if you found another one, report it in a new thread.
