### ISSUE TITLE
Newer versions crashes minecraft at atartup

### ISSUE THREAD

**Issue by mariojuggernaut22** [Keridos/FloodLights#84]
Hello. Everytime I start up Minecraft with newer versions of the floodlight mod, it instantly crashes the game at startup. How could I fix this?
[debug.log](https://github.com/Keridos/FloodLights/files/2496926/debug.log)
[latest.log](https://github.com/Keridos/FloodLights/files/2496927/latest.log)

**Comment by drzpk** [comment]
@mariojuggernaut22 
Is Floodlights mod the only variable here? Does game start normally when you remove it?

**Comment by mariojuggernaut22** [comment]
It doesn't...   Do you know what is at fault?

**Comment by Keridos** [comment]
That seems to be OpenComputers crashing. not Floodlights.
