### ISSUE TITLE
Phantom Light Crashes Wires.

### ISSUE THREAD

**Issue by mariojuggernaut22** [Keridos/FloodLights#85]
Hello, everytime a phantom light covers a duct or wire on my cable it crashes my  game. What can I do to fix it.
[crash-2018-11-02_10.04.25-client.txt](https://github.com/Keridos/FloodLights/files/2542792/crash-2018-11-02_10.04.25-client.txt)

**Comment by drzpk** [comment]
I can't reproduce the crash. Can you provide a screenshot with the exact configuration causing it?

Also, check if the problem still occurs in [the most recent version](https://jenkins.ironhide.de/job/Keridos%20Mods/job/FloodLights-1.12/11/) of the mod installed.

**Comment by drzpk** [comment]
@mariojuggernaut22

**Comment by mariojuggernaut22** [comment]
[image: 2018-11-06_06.47.43.png] WHen one of those faded lights hit a
cable, it crashes the game.

**Comment by drzpk** [comment]
@mariojuggernaut22 

Apparently attaching images via e-mail doesn't work. Could you attach it again here, in this thread?

**Comment by Blue-Beaker** [comment]
[crash-2019-02-02_01.30.18-client.txt](https://github.com/Keridos/FloodLights/files/2822650/crash-2019-02-02_01.30.18-client.txt)
Crashes when placed a ThermalDynamics duct in the light from this mod's floodlight even if the light is turned off.

**Comment by Blue-Beaker** [comment]
I'm using FloodLights-1.12.2-1.3.2-12.jar, and if the light is turned off and re-entered the world, the duct won't crash.
