### ISSUE TITLE
Crash when placing redstone dust in electric flood light.

### ISSUE THREAD

**Issue by somehundred** [Keridos/FloodLights#86]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/6/19 2:22 PM
Description: Updating screen events

java.lang.NoClassDefFoundError: cofh/redstoneflux/api/IEnergyContainerItem
	at de.keridos.floodlights.util.GeneralUtil.isItemStackValidElectrical(GeneralUtil.java:76)
	at de.keridos.floodlights.client.gui.container.ContainerElectricFloodlight$1.func_75214_a(ContainerElectricFloodlight.java:40)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:272)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cofh.redstoneflux.api.IEnergyContainerItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.keridos.floodlights.util.GeneralUtil.isItemStackValidElectrical(GeneralUtil.java:76)
	at de.keridos.floodlights.client.gui.container.ContainerElectricFloodlight$1.func_75214_a(ContainerElectricFloodlight.java:40)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:272)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: de.keridos.floodlights.client.gui.GuiElectricFloodlight

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Andris'/61, l='MpServer', x=346.19, y=67.22, z=-700.22]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (324,4,-910), Chunk: (at 4,0,2 in 20,-57; contains blocks 320,0,-912 to 335,255,-897), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Level time: 180682 game time, 16809 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 69 total; [EntityIronGolem['Iron Golem'/128, l='MpServer', x=323.06, y=54.00, z=-685.04], EntityZombie['Zombie'/129, l='MpServer', x=325.30, y=54.00, z=-683.70], EntityZombie['Zombie'/134, l='MpServer', x=354.74, y=64.00, z=-666.63], EntitySkeleton['Skeleton'/137, l='MpServer', x=328.50, y=64.00, z=-647.50], EntitySpider['Spider'/138, l='MpServer', x=360.64, y=64.00, z=-669.64], EntityVillager['Villager'/12, l='MpServer', x=297.51, y=65.00, z=-705.93], EntityZombieVillager['Villain'/142, l='MpServer', x=325.33, y=56.00, z=-698.00], EntityCreeper['Creeper'/14, l='MpServer', x=321.21, y=65.00, z=-705.50], EntityZombieVillager['Villain'/143, l='MpServer', x=326.27, y=56.00, z=-700.37], EntityZombie['Zombie'/144, l='MpServer', x=328.49, y=56.00, z=-697.53], EntitySpider['Mīlulis'/16, l='MpServer', x=330.30, y=67.10, z=-726.95], EntitySkeleton['Skeleton'/145, l='MpServer', x=325.47, y=56.00, z=-700.83], EntityZombieVillager['Villain'/17, l='MpServer', x=326.44, y=56.00, z=-706.22], EntitySkeleton['Skeleton'/34833, l='MpServer', x=317.50, y=64.00, z=-633.50], EntityCreeper['Creeper'/146, l='MpServer', x=326.19, y=56.00, z=-698.09], EntityZombie['Zombie'/18, l='MpServer', x=326.70, y=56.00, z=-704.30], EntityCreeper['Creeper'/29714, l='MpServer', x=322.50, y=64.00, z=-742.50], EntityCreeper['Creeper'/147, l='MpServer', x=325.95, y=56.00, z=-698.70], EntityCreeper['Creeper'/19, l='MpServer', x=344.50, y=64.00, z=-749.50], EntitySkeleton['Skeleton'/29715, l='MpServer', x=318.50, y=64.00, z=-750.50], EntitySpider['Mīlulis'/20, l='MpServer', x=343.81, y=72.50, z=-707.45], EntityCreeper['Creeper'/148, l='MpServer', x=325.17, y=55.00, z=-682.51], EntityZombie['Zombie'/149, l='MpServer', x=328.43, y=56.00, z=-702.22], EntityCow['Cow'/21, l='MpServer', x=369.22, y=64.00, z=-753.86], EntityZombie['Zombie'/23, l='MpServer', x=363.42, y=64.00, z=-742.27], EntitySpider['Spider'/24, l='MpServer', x=372.95, y=64.00, z=-719.95], EntitySpider['Spider'/26, l='MpServer', x=382.50, y=64.00, z=-774.50], EntitySkeleton['Skeleton'/28, l='MpServer', x=381.50, y=64.00, z=-766.50], EntitySkeleton['Skeleton'/14365, l='MpServer', x=370.56, y=64.00, z=-724.33], EntityZombie['Zombie'/31, l='MpServer', x=372.50, y=64.00, z=-723.50], EntitySkeleton['Skeleton'/14369, l='MpServer', x=386.50, y=64.00, z=-719.50], EntitySpider['Spider'/34, l='MpServer', x=381.47, y=64.00, z=-702.85], EntityChicken['Chicken'/38, l='MpServer', x=388.16, y=64.00, z=-725.54], EntityChicken['Chicken'/39, l='MpServer', x=390.91, y=64.00, z=-720.13], EntityItem['item.item.egg'/40, l='MpServer', x=388.98, y=64.00, z=-725.24], EntityChicken['Chicken'/41, l='MpServer', x=393.10, y=64.00, z=-707.88], EntityChicken['Chicken'/42, l='MpServer', x=391.17, y=64.00, z=-704.26], EntityEnderman['Enderman'/28843, l='MpServer', x=325.50, y=64.00, z=-628.50], EntityItem['item.item.egg'/44, l='MpServer', x=396.73, y=64.00, z=-715.20], EntityEnderman['Enderman'/28844, l='MpServer', x=324.50, y=64.00, z=-629.50], EntityZombie['Zombie'/37296, l='MpServer', x=289.41, y=64.00, z=-704.90], EntitySkeleton['Skeleton'/13361, l='MpServer', x=326.70, y=56.00, z=-698.70], EntityZombie['Zombie'/28851, l='MpServer', x=284.50, y=64.00, z=-776.50], EntitySkeleton['Skeleton'/37299, l='MpServer', x=397.50, y=64.00, z=-728.50], EntityCreeper['Creeper'/37303, l='MpServer', x=290.50, y=64.00, z=-675.50], EntityCreeper['Creeper'/16316, l='MpServer', x=286.50, y=64.00, z=-625.50], EntityEnderman['Enderman'/33340, l='MpServer', x=271.50, y=64.00, z=-662.50], EntityItem['item.item.egg'/1855, l='MpServer', x=393.29, y=64.00, z=-708.74], EntitySpider['Spider'/33345, l='MpServer', x=267.50, y=64.00, z=-659.50], EntitySpider['Mīlulis'/70, l='MpServer', x=299.02, y=64.00, z=-628.54], EntitySkeleton['Skeleton'/37319, l='MpServer', x=350.50, y=64.00, z=-622.50], EntityPlayerSP['Andris'/61, l='MpServer', x=346.19, y=67.22, z=-700.22], EntityZombie['Zombie'/16975, l='MpServer', x=400.80, y=64.00, z=-679.56], EntityZombie['Zombie'/16976, l='MpServer', x=405.50, y=64.00, z=-676.50], EntityCreeper['Creeper'/37330, l='MpServer', x=415.50, y=64.00, z=-727.50], EntityVillager['Villager'/85, l='MpServer', x=314.70, y=65.00, z=-698.70], EntityItem['item.tile.lever'/26453, l='MpServer', x=345.27, y=64.00, z=-703.04], EntitySkeleton['Skeleton'/24150, l='MpServer', x=401.50, y=64.00, z=-673.50], EntityZombie['Zombie'/19159, l='MpServer', x=377.50, y=64.00, z=-719.50], EntityZombie['Zombie'/37336, l='MpServer', x=371.50, y=64.00, z=-708.50], EntityZombie['Zombie'/19163, l='MpServer', x=379.50, y=64.00, z=-731.50], EntitySkeleton['Skeleton'/14054, l='MpServer', x=305.50, y=64.00, z=-623.50], EntityZombie['Zombie'/24166, l='MpServer', x=289.52, y=64.00, z=-706.19], EntityZombie['Zombie'/24167, l='MpServer', x=289.48, y=64.00, z=-706.97], EntityZombie['Zombie'/24168, l='MpServer', x=289.49, y=64.00, z=-712.75], EntitySkeleton['Skeleton'/24171, l='MpServer', x=426.50, y=64.00, z=-625.50], EntityCreeper['Creeper'/24176, l='MpServer', x=426.50, y=64.00, z=-634.50], EntityZombie['Zombie'/117, l='MpServer', x=377.23, y=64.00, z=-658.50], EntitySpider['Mīlulis'/119, l='MpServer', x=408.41, y=64.00, z=-647.04]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 455962728 bytes (434 MB) / 942989312 bytes (899 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 8 total; -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmx1024M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                 | Version      | Source                                           | Signature                                |
	|:--------- |:------------------ |:------------ |:------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft          | 1.12.2       | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | mcp                | 9.42         | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | FML                | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge              | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | securitycraft      | v1.8.10      | [1.12.2]+SecurityCraft+v1.8.10.jar               | None                                     |
	| UCHIJAAAA | flansmod           | 5.5.2        | Flan's Mod-1.12.2-5.5.2.jar                      | None                                     |
	| UCHIJAAAA | flansmodapocalypse | 1.0          | Flan's Mod-1.12.2-5.5.2.jar                      | None                                     |
	| UCHIJAAAA | floodlights        | 1.3.2-10     | FloodLights-1.12.2-1.3.2-10.jar                  | None                                     |
	| UCHIJAAAA | thespotlightmod    | 1.2.0.101    | TheSpotlightMod-1.2.0.101-mc1.12.2-universal.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.5063' Renderer: 'Intel(R) HD Graphics 5500'
	Launched Version: Forge 1.12.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.5063, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Resources
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz

**Comment by Keridos** [comment]
Ah yes, there probably should be a check before that if CoFHCore is
actually loaded.

**Comment by somehundred** [comment]
Looks like a crash occurs when any wrong item is placed into flood light
