### ISSUE TITLE
Future Request: Allow Galacticraft Batteries to Power Floodlights

### ISSUE THREAD

**Issue by TwiliDiamondOcelot** [Keridos/FloodLights#90]
Galacticraft adds a normal battery, a low energy output nuclear battery, and a creative only Infinite battery. It would be nice to see this mod support Galacticraft's batteries.

**Comment by drzpk** [comment]
All electric Floodlights support batteries from Galacticraft. I just check this using Galacticraft Core 1.12.2-4.0.2.229.

If you're using an older version of Galacticraft, try to update it and then let me know if the problem still exists.
