### ISSUE TITLE
java.lang.NoClassDefFoundError: javafx/util/Pair when right-clicking any block from the mod

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Keridos/FloodLights#92]
[crash-2019-12-11_21.59.42-server.txt](https://github.com/Keridos/FloodLights/files/3952102/crash-2019-12-11_21.59.42-server.txt)

Forge 14.23.5.2847, FloodLights 1.12.2-1.4.0-16 (latest CurseForge stable release)

**Comment by drzpk** [comment]
Thanks for the report, the issue has been fixed in the [most recent version](https://www.curseforge.com/minecraft/mc-mods/floodlights/files/2841199).
