### ISSUE TITLE
[1.12.2] Shift clicking items into floodlights causes problems

### ISSUE THREAD

**Issue by fkrisi11** [Keridos/FloodLights#94]
If you shift click any item into the non-electric floodlight, it freezes the game.
I'm not sure if it happens with only non-fuel items or every item however.
I'm also not sure if this happens with other kinds of lamps.
A user reported this problem. He tried multiple items.

Please look into this ^^

**Comment by drzpk** [comment]
@fkrisi11 
I was unable to reproduce this issue on any floodlight in the most recent mod version. Can you provide a crashlog?

**Comment by fkrisi11** [comment]
Trying to find out how to reproduce the issue, but I found a duplication glitch with flood lights meanwhile. Get something like a chest. An items that stacks. Try to shift click the item into a non-electric light. Now you have double the item. Just keep shift clicking.

**Comment by fkrisi11** [comment]
In fact it duplicates everything that can stack. But I couldn't make my game freeze though :\

**Comment by fkrisi11** [comment]
I could not replicate the freezing bug... sorry about that :/

But hey, at least I found that dupe bug haha

**Comment by drzpk** [comment]
@fkrisi11 
I can't reproduce this item duplication issue as well. 😶

I've tried everything:
* shift-clicking player's inventory slot
* shift-clicking floodlight's slots
* shift-clicking on a floodlight block
* \+ the above options but with different game mode, full and empty player's inventory, fuel and non-fuel items.

Need more details to narrow down this issue hunt:
1. What's your game mode?
2. Are you shift-clicking on the floodlight block or somewhere in the floodlight's GUI?
3. What blocks/items are in floodlight's slots when this bug occurs?

**Comment by fkrisi11** [comment]
So here it is in a 9MB gif.
I am not in creative, I don't have cheats on in JEI.
I do have MouseTweaks installed. (But I don't think this is a problem)

For every duplication I just shift click stone from the player's inventory into the non-electric FloodLight.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26310365/79373435-d8d56480-7f56-11ea-9d15-39d26fc84556.gif)

**Comment by fkrisi11** [comment]
@IlynPayne  Is there anything else I can do to help you guys with finding out the problem?

**Comment by drzpk** [comment]
@fkrisi11 No, thanks. I just didn't have time to look into this issue, hence the delay.

**Comment by fkrisi11** [comment]
I understand. Just want to help as much as possible ^^

**Comment by drzpk** [comment]
I was finally able to find the cause. Turns out shift-clicking didn't work properly only for the first and second hotbar slots - that's why I was couldn't reproduce this bug until you provided the GIF (I didn't use these slots).

Anyway, thanks for the patience, new version has been a;ready uploaded to CurseForge.

**Comment by fkrisi11** [comment]
Thank you so so so much ^^
